# Generated by Django 5.0.4 on 2024-06-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='RegUser',
        ),
    ]
